POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIU6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzbWl0aCIsImlkIjoiNWZjOTY0ZjNmMGYyN2UzZDQ1ZDI3NmFlIiwiaWF0IjoxNjA3MDM3NjQzfQ.MO6BXCiPH-SenvNpUFkktXIgKg-xXRNJjR2eqdJCTzY

{
    "content": "SPAs use token auth!",
    "important": true
}